version: '2'

services:
  postgresql:
    image: docker.io/bitnami/postgresql:10
    volumes:
      - 'postgresql_data:/bitnami/postgresql'
    environment:
      - POSTGRESQL_DATABASE=bitnami_airflow
      - POSTGRESQL_USERNAME=bn_airflow
      - POSTGRESQL_PASSWORD=bitnami1
      # ALLOW_EMPTY_PASSWORD is recommended only for development.
      - ALLOW_EMPTY_PASSWORD=yes
    ports:
      - 5433:5432
  redis:
    image: docker.io/bitnami/redis:7.0
    volumes:
      - 'redis_data:/bitnami'
    environment:
      # ALLOW_EMPTY_PASSWORD is recommended only for development.
      - ALLOW_EMPTY_PASSWORD=yes
  airflow-scheduler:
    image: docker.io/bitnami/airflow-scheduler:2
    volumes:
      - ./dags:/opt/bitnami/airflow/dags
    environment:
      - AIRFLOW_FERNET_KEY=1VmNKI7ykg0cZx9vnnoyAiCclAkzK9RqIqo_J0b3sbs=
      - AIRFLOW_SECRET_KEY=ukqJH7YOQYDnjyjsaaVRx4RUaXD9oRgT
      - AIRFLOW_DATABASE_NAME=bitnami_airflow
      - AIRFLOW_DATABASE_USERNAME=bn_airflow
      - AIRFLOW_DATABASE_PASSWORD=bitnami1
      - AIRFLOW_EXECUTOR=LocalExecutor
      - AIRFLOW_LOAD_EXAMPLES=no
#      - AIRFLOW_EXECUTOR=CeleryExecutor
      - AIRFLOW_WEBSERVER_HOST=airflow
  airflow-worker:
    image: docker.io/bitnami/airflow-worker:2
    environment:
      - AIRFLOW_FERNET_KEY=1VmNKI7ykg0cZx9vnnoyAiCclAkzK9RqIqo_J0b3sbs=
      - AIRFLOW_SECRET_KEY=ukqJH7YOQYDnjyjsaaVRx4RUaXD9oRgT
      - AIRFLOW_DATABASE_NAME=bitnami_airflow
      - AIRFLOW_DATABASE_USERNAME=bn_airflow
      - AIRFLOW_DATABASE_PASSWORD=bitnami1
      - AIRFLOW_EXECUTOR=LocalExecutor
#      - AIRFLOW_EXECUTOR=CeleryExecutor
      - AIRFLOW_WEBSERVER_HOST=airflow
  airflow:
    image: docker.io/bitnami/airflow:2
#    volumes:
#      - ./dags:/opt/bitnami/airflow/dags
    environment:
      - AIRFLOW_FERNET_KEY=1VmNKI7ykg0cZx9vnnoyAiCclAkzK9RqIqo_J0b3sbs=
      - AIRFLOW_SECRET_KEY=ukqJH7YOQYDnjyjsaaVRx4RUaXD9oRgT
      - AIRFLOW_DATABASE_NAME=bitnami_airflow
      - AIRFLOW_DATABASE_USERNAME=bn_airflow
      - AIRFLOW_DATABASE_PASSWORD=bitnami1
      - AIRFLOW_EXECUTOR=LocalExecutor
      - AIRFLOW_LOAD_EXAMPLES=no
#      - AIRFLOW_EXECUTOR=CeleryExecutor
    ports:
      - '8080:8080'
volumes:
  postgresql_data:
    driver: local
  redis_data:
    driver: local
  dags: